# Generated by Django 4.0.6 on 2022-08-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=100)),
                ('select_file', models.FileField(upload_to='user_uploaded')),
                ('dics', models.TextField()),
            ],
        ),
    ]
